---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: demo
spec:
  encryptedData:
    password: AgAzrjYp0JR5zgzTjRrBxZZaBHVwjQVp1qSX+roLAjKWrNFkItU3n/r85aM2QfjPIhTqPi5HY3DSxjh/Nss7qVChcJ8ww1jiN+wHoRBsAytH2Xpa/w/qexAf7Kyy+irBS3DhEdUNB7H+OxO5qiLI4GGEfgjWLrM9K8eWiOEy+B2xvBFcwkyjM75saGIIvBULU+LmbfpEbHfyvwdAI0iIOyNGNZqJ1w93F32UT5JPGKFGZYQDvRRsxhyRZZMWdAavfPbuMcv5Pj3N28/XnK62/t2tYfe4/w4RH2BNvIeI7UrIbGrhd9dWPBVh+0jdh2iOJyIDk1R+677Fq6LF8IwQKf+7UbYgTt5GA0UMgR0M7eiRs4TsarDn/dHK0lizFuSL0ZLzWQRlepPNgJ6RdVJS+k67MAFjIt+UGQq4Tw5XUwVnRDbGoCbG+Ihi2z2H6Xbq+jWissgAmWVEHSphUnqDC6lofAKVkaMtN0F0JA76GtldQUOQlObt1gXZ7RfTgo1F55t/biqfSQO8/PVvY9KHd+r7LJyOGV5TvxfBWZmELyh/+pV+VH/X6n0NdnCszxO8K8q7a9kyex+qaHb4ndvHNRO5cDz5dLj+Ye5L4Q7xfjGgnly2oWqaJP/aqAN1bWs1uaa2TbTJBmRHnvfyjr1QX40qckZ6qddeUnkU4s9NP0Z6xoFfITDtQmBXMQzZLs6PlMXIXgamAiZdo870/pp8AAU=
    username: AgByqwkwJpfje7biRmuqAilJp+ezeOr1SL7YyyTH/TvbyGF6ZsfMKyVaw2P0bz9uC9TdEMQEG76QpENO6BYyfTyI1j2roqTYFVNhHq/zvWdSXZcH6KENBB8spvkrX0f+95UxwDbXTOEpddJgB5ZtROCTz5Kv/w+VoIJSkPqF/3Slt/6VMPckzrBQeOOJQel1+JldOjNpWlojCCIRUdYBKeIMpPQRHSOYLwKObQ5EwVpIQHKnOazhaGoQV5844fPmStASHWjSlDG7x5yAT2uCiOWTxpvoWTHz4EPvsjaKYhFPKWKfgjlL/I/iDoYtcu8WLcQwiJybqR7vipEhoOifEe3YIg0NQwlGQmYXuG3523+Rl/g7CepQoeZWxk60QnHVOEPchwFXB7fTgVi2IEcHtemYRCMTcj4L4zo8r4DnG7aIwqT1hJG4Cd7QJnezy91joLg6bX1s4sQNL3Z7VMHsevkTJ4QR5k1Hpdzh09FYevuX44ggASOqUgBObHbHpmGcXfVWFO55WLVOB6XaNbTDv3actlNZlrO66UhhHsmWGqG4XGCi+JpK04kZ7nfLltuwP367So/Nt5L+1bQemykEO/se5ZnvEsCSA1oWNzL/fzs/YTdxjisVAWa/9JBZl3AT1FfLrcP0S7r3I/ebCpgnkVaXcIk8UP3PnInOA/2lDWE4ta7hHIz9VGbUaeCc/MAYkIFuj40dOQ==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: demo
