apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-system
spec:
  template:
    metadata:
      annotations:
        checkov.io/skip1: CKV_K8S_17=hostPID required for kube-bench
        checkov.io/skip2: CKV_K8S_23=Runs as root because host inspection is required
        checkov.io/skip3: CKV_K8S_38=Needs service account token
    spec:
      hostPID: true
      restartPolicy: Never

      automountServiceAccountToken: true

      containers:
        - name: kube-bench
          image: aquasec/kube-bench:v0.14.1

          command:
            - kube-bench

          args:
            - "--benchmark"
            - "k3s-cis-1.24"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: etc
              mountPath: /etc
              readOnly: true

            - name: var
              mountPath: /var
              readOnly: true

            - name: usr-bin
              mountPath: /usr/bin
              readOnly: true

            - name: usr-local-bin
              mountPath: /usr/local/bin
              readOnly: true

      volumes:
        - name: etc
          hostPath:
            path: /etc

        - name: var
          hostPath:
            path: /var

        - name: usr-bin
          hostPath:
            path: /usr/bin

        - name: usr-local-bin
          hostPath:
            path: /usr/local/bin
