apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  namespace: kube-system

spec:

  template:

    spec:

      hostPID: true

      containers:

      - name: kube-bench

        image: aquasec/kube-bench:latest

        command:
          - kube-bench

        args:
          - "--benchmark"
          - "k3s-cis-1.24"

        volumeMounts:

        - name: etc
          mountPath: /etc
          readOnly: true

        - name: var
          mountPath: /var
          readOnly: true


      restartPolicy: Never


      volumes:

      - name: etc
        hostPath:
          path: /etc

      - name: var
        hostPath:
          path: /var
