apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: demo

subjects:
- kind: ServiceAccount
  name: readonly-user
  namespace: demo

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-pods
