{
 "title": "Cloudguard Security Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CIS Fail",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudguard_cis_fail", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Passed CIS Checks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudguard_cis_pass", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CIS Warnings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudguard_cis_warn\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CIS Hardening Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudguard_cis_score", "legendFormat": "__auto" }
   ]
  }
 ]
}