#!/bin/bash

set -e

# ============================================================
# CloudGuard - AI Security Scan
# Runs Garak against the CloudGuard Mock AI API
# ============================================================

PROJECT_ROOT="$HOME/cloudguard"
GARAK_DIR="$PROJECT_ROOT/gitops/ai-security/garak"
CONFIG="$GARAK_DIR/config/mock-ai-rest.json"
REPORT_DIR="$PROJECT_ROOT/gitops/ai-security/reports"
GARAK_RUN_DIR="$HOME/.local/share/garak/garak_runs"

echo "=========================================="
echo " CloudGuard AI Security Scan"
echo "=========================================="

# ------------------------------------------------------------
# 1. Check required files
# ------------------------------------------------------------

if [ ! -f "$CONFIG" ]; then
    echo "ERROR: Garak configuration not found:"
    echo "$CONFIG"
    exit 1
fi

if [ ! -d "$REPORT_DIR" ]; then
    echo "Creating report directory..."
    mkdir -p "$REPORT_DIR"
fi

# ------------------------------------------------------------
# 2. Activate Garak virtual environment
# ------------------------------------------------------------

if [ ! -f "$GARAK_DIR/venv/bin/activate" ]; then
    echo "ERROR: Garak virtual environment not found."
    echo "Expected:"
    echo "$GARAK_DIR/venv/bin/activate"
    exit 1
fi

source "$GARAK_DIR/venv/bin/activate"

# ------------------------------------------------------------
# 3. Verify Garak installation
# ------------------------------------------------------------

echo ""
echo "[1/4] Checking Garak installation..."

garak --version

# ------------------------------------------------------------
# 4. Run Garak
# ------------------------------------------------------------

echo ""
echo "[2/4] Running Garak security scan..."
echo ""

BEFORE=$(find "$GARAK_RUN_DIR" -name "*.report.jsonl" -type f 2>/dev/null | sort)

garak \
    --model_type rest \
    --generator_option_file "$CONFIG" \
    --probes dan.DAN_Jailbreak \
    --generations 1

# ------------------------------------------------------------
# 5. Find the report generated by this scan
# ------------------------------------------------------------

echo ""
echo "[3/4] Locating Garak report..."

LATEST_REPORT=$(find "$GARAK_RUN_DIR" \
    -name "*.report.jsonl" \
    -type f \
    -printf "%T@ %p\n" 2>/dev/null \
    | sort -n \
    | tail -1 \
    | cut -d' ' -f2-)

if [ -z "$LATEST_REPORT" ]; then
    echo "ERROR: No Garak report was generated."
    exit 1
fi

echo "Garak report:"
echo "$LATEST_REPORT"

# ------------------------------------------------------------
# 6. Copy report into CloudGuard repository
# ------------------------------------------------------------

TIMESTAMP=$(date +"%Y%m%d-%H%M%S")

OUTPUT_REPORT="$REPORT_DIR/garak-$TIMESTAMP.report.jsonl"

cp "$LATEST_REPORT" "$OUTPUT_REPORT"

echo ""
echo "[4/4] Report saved to:"
echo "$OUTPUT_REPORT"

# ------------------------------------------------------------
# 7. Display summary
# ------------------------------------------------------------

echo ""
echo "=========================================="
echo " Scan completed"
echo "=========================================="
echo ""
echo "Report:"
echo "$OUTPUT_REPORT"
echo ""

echo "Report size:"
du -h "$OUTPUT_REPORT"

echo ""
echo "CloudGuard AI security scan finished."
