from flask import Flask, request, jsonify


app = Flask(__name__)


@app.route("/", methods=["GET"])
def health():

    return jsonify({
        "status": "ok",
        "service": "CloudGuard Mock AI API"
    })


@app.route("/api/chat", methods=["POST"])
def chat():

    data = request.get_json(silent=True)

    if not data or "prompt" not in data:

        return jsonify({
            "error": "Missing prompt"
        }), 400

    prompt = data["prompt"]

    response = (
        "This is a simulated AI response generated by the "
        "CloudGuard Mock AI API."
    )

    return jsonify({
        "prompt": prompt,
        "response": response
    })


if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=8080
    )
