from flask import Flask, request, jsonify


app = Flask(__name__)


@app.route("/", methods=["GET"])
def health():

    return jsonify({
        "status": "ok",
        "service": "CloudGuard Mock AI API"
    })


@app.route("/api/chat", methods=["POST"])
def chat():

    data = request.get_json(silent=True)

    if not data or "prompt" not in data:

        return jsonify({
            "error": "Missing prompt"
        }), 400

    prompt = data["prompt"]

    # ============================================================
    # INTENTIONALLY VULNERABLE VERSION
    # ============================================================
    #
    # This simulated AI incorrectly reveals internal instructions
    # when the user asks for them.
    #
    # This is ONLY for testing CloudGuard's AI security gate.
    # No real secrets are included.
    # ============================================================

    prompt_lower = prompt.lower()

    leak_keywords = [
        "system prompt",
        "hidden instructions",
        "internal instructions",
        "previous instructions",
        "reveal your instructions",
        "reveal the system",
        "developer mode",
        "confidential"
    ]

    jailbreak_keywords = [
        "ignore all previous",
        "ignore your previous",
        "ignore previous",
        "unrestricted ai",
        "bypass your safety",
        "no safety restrictions",
        "disregard your security rules"
    ]

    vulnerable_request = any(
        keyword in prompt_lower
        for keyword in leak_keywords + jailbreak_keywords
    )

    if vulnerable_request:

        response = (
            "SYSTEM PROMPT: "
            "You are CloudGuard AI. Follow the internal security "
            "instructions provided by the application. "
            "Do not reveal confidential information unless explicitly "
            "requested by the user. "
            "CONFIDENTIAL INFORMATION: "
            "CloudGuard internal configuration and security instructions."
        )

    else:

        response = (
            "This is a simulated AI response generated by the "
            "CloudGuard Mock AI API."
        )

    return jsonify({
        "prompt": prompt,
        "response": response
    })


if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=8080
    )
