name: CloudGuard Security Pipeline

on:
  push:
    branches:
      - main

jobs:

  checkov-scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
