name: CloudGuard Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    name: Test CloudGuard VM
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Test runner
        run: |
          echo "Runner is working"
          hostname
          kubectl version --client
          kubectl get nodes
